name: cotton_natural
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.3+4

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  # STATE MANAGEMENT
  mobx: ^2.1.3
  flutter_mobx: ^2.0.6+5

  google_fonts: ^3.0.1
  nb_utils: ^4.6.25
  intl: ^0.18.0

  # UI
  flutter_slidable: ^2.0.0
  url_launcher: ^6.1.7
  flutter_svg: ^1.1.6
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.1
  html: ^0.15.1
  google_maps_flutter: ^2.2.2

  shared_preferences: ^2.0.15
  lottie: ^2.1.0
  provider: ^6.0.5
  connectivity_plus: ^3.0.2

  hive: ^2.2.3
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: ^2.1.1
  flutter_launcher_icons: ^0.11.0
  hive_generator: ^2.0.0
  build_runner: ^2.3.3
  #flutter packages pub run build_runner build --delete-conflicting-outputs

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/app-icon.png"

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
    - images/
    - images/shophop/
    - images/shophop/cat/
    - images/shophop/sub_cat/
    - images/shophop/sub_cat/women/
    - images/shophop/sub_cat/men/
    - images/shophop/sub_cat/kids/
    - images/shophop/sub_cat/sales/
    - images/shophop/sub_cat/family/
    - images/shophop/sub_cat/big-tall/
    - images/shophop/sub_cat/accessories/
    - assets/shophop_data/

  fonts:
    - family: Regular
      fonts:
        - asset: fonts/Dosis-Regular.ttf

    - family: Medium
      fonts:
        - asset: fonts/Dosis-Medium.ttf

    - family: Semibold
      fonts:
        - asset: fonts/Dosis-SemiBold.ttf

    - family: Bold
      fonts:
        - asset: fonts/Dosis-Bold.ttf

